#ifndef __BLUEZ_DBUS_H__
#define __BLUEZ_DBUS_H__

#define BLUEZ_DBUS                                  "org.bluez"

#define INTERFACE_ADAPTER                           "org.bluez.Adapter1"
#define INTERFACE_AGENT                             "org.bluez.Agent1"
#define INTERFACE_AGENT_MANAGER                     "org.bluez.AgentManager1"
#define INTERFACE_DEVICE                            "org.bluez.Device1"
#define INTERFACE_ADV                               "org.bluez.LEAdvertisement1"
#define INTERFACE_ADV_MANAGER                       "org.bluez.LEAdvertisingManager1"
#define INTERFACE_GATT_MANAGER                      "org.bluez.GattManager1"
#define INTERFACE_CHARACTERISTIC                    "org.bluez.GattCharacteristic1"
#define INTERFACE_DESCRIPTOR                        "org.bluez.GattDescriptor1"
#define INTERFACE_SERVICE                           "org.bluez.GattService1"
#define INTERFACE_MEDIA_ENDPOINT                    "org.bluez.MediaEndpoint1"
#define INTERFACE_MEDIA_PLAYER                      "org.bluez.MediaPlayer1"
#define INTERFACE_MEDIA_CONTROL                     "org.bluez.MediaControl1"
#define INTERFACE_MEDIA_TRANSPORT                   "org.bluez.MediaTransport1"
#define INTERFACE_OBJECT_MANAGER                    "org.freedesktop.DBus.ObjectManager"
#define INTERFACE_PROPERTIES                        "org.freedesktop.DBus.Properties"

#define ADAPTER_METHOD_START_DISCOVERY              "StartDiscovery"
#define ADAPTER_METHOD_STOP_DISCOVERY               "StopDiscovery"
#define ADAPTER_METHOD_REMOVE_DEVICE                "RemoveDevice"
#define ADAPTER_METHOD_SET_DISCOVERY_FILTER         "SetDiscoveryFilter"
#define ADAPTER_PROPERTY_POWERED                    "Powered"
#define ADAPTER_PROPERTY_POWER_STATE                "PowerState"
#define ADAPTER_PROPERTY_DISCOVERING                "Discovering"
#define ADAPTER_PROPERTY_ADDRESS                    "Address"
#define ADAPTER_PROPERTY_DISCOVERABLE               "Discoverable"
#define ADAPTER_PROPERTY_CONNECTABLE                "Connectable"
#define ADAPTER_PROPERTY_ALIAS                      "Alias"

#define AGENT_MANAGER_METHOD_REGISTER               "RegisterAgent"
#define AGENT_MANAGER_METHOD_UNREGISTER             "UnregisterAgent"
#define AGENT_MANAGER_METHOD_REQUEST_DEFAULT        "RequestDefaultAgent"

#define AGENT_METHOD_RELEASE                        "Release"
#define AGENT_METHOD_REQUEST_PIN_CODE               "RequestPinCode"
#define AGENT_METHOD_DISPLAY_PIN_CODE               "DisplayPinCode"
#define AGENT_METHOD_REQUEST_PASSKEY                "RequestPasskey"
#define AGENT_METHOD_DISPLAY_PASSKEY                "DisplayPasskey"
#define AGENT_METHOD_REQUEST_CONFIRMATION           "RequestConfirmation"
#define AGENT_METHOD_REQUEST_AUTHORIZATION          "RequestAuthorization"
#define AGENT_METHOD_AUTHORIZESERVICE               "AuthorizeService"
#define AGENT_METHOD_CANCEL                         "Cancel"

#define ADV_MANAGER_METHOD_REGISTER                 "RegisterAdvertisement"
#define ADV_MANAGER_METHOD_UNREGISTER               "UnregisterAdvertisement"
#define ADV_MANAGER_PROPERTY_ACTIVE_INSTANCES       "ActiveInstances"
#define ADV_MANAGER_PROPERTY_SUPPORTED_INSTANCES    "SupportedInstances"
#define ADV_MANAGER_PROPERTY_SUPPORTED_INCLUDES     "SupportedIncludes"
#define ADV_MANAGER_PROPERTY_SUPPORTED_SECONDARY_CHANNELS     "SupportedSecondaryChannels"

#define ADV_METHOD_RELEASE                          "Release"
#define ADV_PROPERTY_TYPE                           "Type"
#define ADV_PROPERTY_SERVICE_UUIDS                  "ServiceUUIDs"
#define ADV_PROPERTY_MANUFACTURE_DATA               "ManufacturerData"
#define ADV_PROPERTY_SERVICE_DATA                   "ServiceData"
#define ADV_PROPERTY_DISCOVERABLE                   "Discoverable"
#define ADV_PROPERTY_DISCOVERABLE_TIMEOUT           "DiscoverableTimeout"
#define ADV_PROPERTY_INCLUDES                       "Includes"
#define ADV_PROPERTY_LOCAL_NAME                     "LocalName"
#define ADV_PROPERTY_APPEARANCE                     "Appearance"
#define ADV_PROPERTY_DURATION                       "Duration"
#define ADV_PROPERTY_TIMEOUT                        "Timeout"
#define ADV_PROPERTY_SECONDARY_CHANNEL              "SecondaryChannel"
#define ADV_PROPERTY_MIN_INTERVAL                   "MinInterval"
#define ADV_PROPERTY_MAX_INTERVAL                   "MaxInterval"
#define ADV_PROPERTY_TX_POWER                       "TxPower"

#define DEVICE_METHOD_CONNECT                       "Connect"
#define DEVICE_METHOD_PAIR                          "Pair"
#define DEVICE_METHOD_DISCONNECT                    "Disconnect"
#define DEVICE_SIGNAL_CONNECTED                     "Connected"
#define DEVICE_SIGNAL_DISCONNECTED                  "Disconnected"
#define DEVICE_PROPERTY_ADDRESS                     "Address"
#define DEVICE_PROPERTY_ADDRESS_TYPE                "AddressType"
#define DEVICE_PROPERTY_ALIAS                       "Alias"
#define DEVICE_PROPERTY_NAME                        "Name"
#define DEVICE_PROPERTY_PAIRED                      "Paired"
#define DEVICE_PROPERTY_RSSI                        "RSSI"
#define DEVICE_PROPERTY_UUIDS                       "UUIDs"
#define DEVICE_PROPERTY_MANUFACTURER_DATA           "ManufacturerData"
#define DEVICE_PROPERTY_SERVICE_DATA                "ServiceData"
#define DEVICE_PROPERTY_TRUSTED                     "Trusted"
#define DEVICE_PROPERTY_TXPOWER                     "TxPower"
#define DEVICE_PROPERTY_CONNECTED                   "Connected"
#define DEVICE_PROPERTY_SERVICES_RESOLVED           "ServicesResolved"

#define CHARACTERISTIC_METHOD_READ_VALUE            "ReadValue"
#define CHARACTERISTIC_METHOD_WRITE_VALUE           "WriteValue"
#define CHARACTERISTIC_METHOD_STOP_NOTIFY           "StopNotify"
#define CHARACTERISTIC_METHOD_START_NOTIFY          "StartNotify"
#define CHARACTERISTIC_PROPERTY_NOTIFYING           "Notifying"
#define CHARACTERISTIC_PROPERTY_VALUE               "Value"
#define CHARACTERISTIC_METHOD_CONFIRM               "Confirm"

#define DESCRIPTOR_METHOD_READ_VALUE                "ReadValue"
#define DESCRIPTOR_METHOD_WRITE_VALUE               "WriteValue"

#define MEDIA_PLAYER_METHOD_PLAY                    "Play"
#define MEDIA_PLAYER_METHOD_PAUSE                   "Pause"
#define MEDIA_PLAYER_METHOD_STOP                    "Stop"
#define MEDIA_PLAYER_METHOD_NEXT                    "Next"
#define MEDIA_PLAYER_METHOD_PREVIOUS                "Previous"
#define MEDIA_PLAYER_METHOD_SEEK                    "Seek"
#define MEDIA_PLAYER_PROPERTY_DEVICE                "Device"
#define MEDIA_PLAYER_PROPERTY_NAME                  "Name"
#define MEDIA_PLAYER_PROPERTY_TYPE                  "Type"
#define MEDIA_PLAYER_PROPERTY_STATUS                "Status"
#define MEDIA_PLAYER_PROPERTY_POSITION              "Position"
#define MEDIA_PLAYER_PROPERTY_TRACK                 "Track"

#define MEDIA_TRANSPORT_METHOD_ACQUIRE              "Acquire"
#define MEDIA_TRANSPORT_METHOD_TRY_ACQUIRE          "TryAcquire"
#define MEDIA_TRANSPORT_METHOD_SELECT               "Select"
#define MEDIA_TRANSPORT_METHOD_UNSELECT             "Unselect"
#define MEDIA_TRANSPORT_PROPERTY_DEVICE             "Device"
#define MEDIA_TRANSPORT_PROPERTY_UUID               "UUID"
#define MEDIA_TRANSPORT_PROPERTY_CODEC              "Codec"
#define MEDIA_TRANSPORT_PROPERTY_CONFIG             "Configuration"
#define MEDIA_TRANSPORT_PROPERTY_STATE              "State"
#define MEDIA_TRANSPORT_PROPERTY_DELAY              "Delay"
#define MEDIA_TRANSPORT_PROPERTY_VOLUME             "Volume"
#define MEDIA_TRANSPORT_PROPERTY_ENDPOINT           "Endpoint"
#define MEDIA_TRANSPORT_PROPERTY_LOCATION           "Location"
#define MEDIA_TRANSPORT_PROPERTY_METADATA           "Metadata"
#define MEDIA_TRANSPORT_PROPERTY_LINKS              "Links"
#define MEDIA_TRANSPORT_PROPERTY_QOS                "QoS"

#define OBJECT_MANAGER_METHOD_GET_MANAGED_OBJECTS   "GetManagedObjects"
#define OBJECT_MANAGER_SIGNAL_INTERFACE_ADDED       "InterfacesAdded"
#define OBJECT_MANAGER_SIGNAL_INTERFACE_REMOVED     "InterfacesRemoved"

#define PROPERTIES_METHOD_GET                       "Get"
#define PROPERTIES_METHOD_GET_ALL                   "GetAll"
#define PROPERTIES_METHOD_SET                       "Set"
#define PROPERTIES_SIGNAL_CHANGED                   "PropertiesChanged"

#define BLUEZ_DBUS_CONNECTION_CALL_TIMEOUT          20000

#endif //__BLUEZ_DBUS_H__